name: Deploy development

on:
  push:
    branches:
      - main
      - feature/20240919_workflow_refactor_v2

jobs:
  build-application:
    name: Build application
    uses: ./.github/workflows/build-application.yml

  build-push-ecr:
    name: Push ECR
    uses: ./.github/workflows/build-push-ecr.yml
    needs: build-application
    with:
      environment: development
      service-name: history
    secrets: inherit

  deploy-ecs:
    name: Deploy ECS
    uses: ./.github/workflows/deploy-ecs.yml
    needs: build-push-ecr
    with:
      environment: development
      ecr-image: ${{ needs.build-push-ecr.outputs.ecr-image }}
      cluster-name: core-services
      service-name: history
      cluster-suffix: g8M6HWc0Cdph
      service-suffix: QUyk6UvlrbdB
    secrets: inherit
